//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GRH_BO.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DIPLOME
    {
        public decimal IDDIPLOME { get; set; }
        public string LIBELLEDIPLOME { get; set; }
        public string PARCOURS { get; set; }
        public int CATEGORIE { get; set; }
        public string CORPS { get; set; }
    }
}
