//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GRH_BO.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GRHEntities : DbContext
    {
        public GRHEntities()
            : base("name=GRHEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ACCES> ACCES { get; set; }
        public virtual DbSet<AVANCEMENT> AVANCEMENT { get; set; }
        public virtual DbSet<AVERTISSEMENT> AVERTISSEMENT { get; set; }
        public virtual DbSet<CONGE> CONGE { get; set; }
        public virtual DbSet<CONTRAT> CONTRAT { get; set; }
        public virtual DbSet<DIPLOME> DIPLOME { get; set; }
        public virtual DbSet<FORUM> FORUM { get; set; }
        public virtual DbSet<GRADE> GRADE { get; set; }
        public virtual DbSet<HISTORIQUE> HISTORIQUE { get; set; }
        public virtual DbSet<INTEGRATION> INTEGRATION { get; set; }
        public virtual DbSet<LOCALITE> LOCALITE { get; set; }
        public virtual DbSet<PERSONNELS> PERSONNELS { get; set; }
        public virtual DbSet<PROFIL> PROFIL { get; set; }
        public virtual DbSet<R_PERSO_AVANCEMENT> R_PERSO_AVANCEMENT { get; set; }
        public virtual DbSet<R_PERSO_AVERTISSEMENT> R_PERSO_AVERTISSEMENT { get; set; }
        public virtual DbSet<R_PERSO_CONGE> R_PERSO_CONGE { get; set; }
        public virtual DbSet<R_PERSO_CONTRAT> R_PERSO_CONTRAT { get; set; }
        public virtual DbSet<R_PROFIL_ACCES> R_PROFIL_ACCES { get; set; }
        public virtual DbSet<R_USER_FORUM> R_USER_FORUM { get; set; }
        public virtual DbSet<R_USER_HISTORIQUE> R_USER_HISTORIQUE { get; set; }
        public virtual DbSet<RECLASSEMENT> RECLASSEMENT { get; set; }
        public virtual DbSet<RETRAITE> RETRAITE { get; set; }
        public virtual DbSet<SERVICE> SERVICE { get; set; }
        public virtual DbSet<STATUT> STATUT { get; set; }
        public virtual DbSet<USER> USER { get; set; }
    }
}
