//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GRH_BO.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOCALITE
    {
        public decimal IDLOCALITE { get; set; }
        public string LOCALITE1 { get; set; }
        public string DIRECTION { get; set; }
    }
}
