//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GRH_BO.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class R_PERSO_CONGE
    {
        public decimal IDCONGE { get; set; }
        public decimal IDPERSONNEL { get; set; }
        public System.DateTime DATEDEBCONGE { get; set; }
        public System.DateTime DATEFINCONGE { get; set; }
        public int JOURSPRIS { get; set; }
        public string MOTIF { get; set; }
    }
}
