//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GRH_BO.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER
    {
        public decimal IDUSER { get; set; }
        public decimal IDPROFIL { get; set; }
        public string LOGINUSER { get; set; }
        public string MDP { get; set; }
        public string NOMUSER { get; set; }
        public string PRENOMUSER { get; set; }
        public string EMAIL { get; set; }
        public string TELINSCRIPTION { get; set; }
        public string PHOTOUSER { get; set; }
        public System.DateTime DATEPROFIL { get; set; }
    }
}
